workflows:
  android-ios-workflow:
    name: Android & iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.appEspecializacion"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build iOS (Unsigned IPA)
        script: |
          flutter build ios --release --no-codesign

          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/

          cd build/ios/ipa
          zip -qr AppEspecializacion.ipa Payload
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/AppEspecializacion.ipa
    publishing:
      email:
        recipients:
          - 74934503@continental.edu.pe
        notify:
          success: true
          failure: true
